import express from 'express';
import { google } from 'googleapis';
import jwt from 'jsonwebtoken';
import User from '../models/User.js';
const router = express.Router();

// Initialize OAuth2 client - will be created on first use
let oauth2Client = null;

// Helper function to ensure OAuth2 client is initialized
function getOAuth2Client() {
  if (!oauth2Client) {
    // Validate credentials on first use
    if (!process.env.GOOGLE_CLIENT_ID || !process.env.GOOGLE_CLIENT_SECRET || !process.env.GOOGLE_REDIRECT_URI) {
      throw new Error('Missing Google OAuth environment variables: GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_REDIRECT_URI');
    }
    
    oauth2Client = new google.auth.OAuth2(
      process.env.GOOGLE_CLIENT_ID,
      process.env.GOOGLE_CLIENT_SECRET,
      process.env.GOOGLE_REDIRECT_URI
    );
  }
  return oauth2Client;
}

const SCOPES = [
  'openid',
  'email',
  'profile',
  'https://www.googleapis.com/auth/gmail.metadata'
];

/**
 * GET /api/auth/google/login
 * Generates the Google OAuth authorization URL and redirects user to Google's consent screen
 */
router.get('/google/login', (req, res) => {
  try {
    // Generate authorization URL with scopes
    const client = getOAuth2Client();
    const authUrl = client.generateAuthUrl({
      access_type: 'offline',
      prompt: 'consent',
       // Request refresh token
      scope: SCOPES,
      // state is useful for CSRF protection - generated by the client
    });

    res.redirect(authUrl);
  } catch (error) {
    console.error('Error generating authorization URL:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to generate authorization URL',
      error: error.message,
    });
  }
});

/**
 * GET /api/auth/google/login/callback
 * Exchanges the authorization code for access token and fetches user info
 */
router.get('/google/login/callback', async (req, res) => {
  try {
    const { code } = req.query;

    // Validate that authorization code is provided
    if (!code) {
      return res.status(400).json({
        success: false,
        message: 'Authorization code is missing from callback',
      });
    }

    console.log('Exchanging authorization code for tokens...');

    // Exchange authorization code for access token
    const client = getOAuth2Client();
    const { tokens } = await client.getToken(code);

    // Set credentials so we can use the oauth2Client to access user info
    client.setCredentials(tokens);

    console.log('Tokens received. Fetching user info...');

    // Initialize the oauth2 service to fetch user information
    const oauth2 = google.oauth2({
      auth: client,
      version: 'v2',
    });

    // Get user info from Google
    const userInfo = await oauth2.userinfo.get();

    console.log('User info retrieved:', userInfo.data);

    const { email, name, picture } = userInfo.data;

    // Validate user data
    if (!email) {
      return res.status(400).json({
        success: false,
        message: 'Email not provided by Google',
      });
    }

    // Check if user already exists in database
    let user = await User.findOne({ email });

    if (!user) {
      // Create new user if doesn't exist
      console.log('Creating new user:', email);
      user = new User({
  name: name || email.split('@')[0],
  email: email.toLowerCase(),
  password: null,
  googleId: userInfo.data.id,
  authMethod: 'google',
  googleAccessToken: tokens.access_token,
  googleRefreshToken: tokens.refresh_token,
  gmailConnected: true,
});
      await user.save();
      console.log('User created successfully');
    } else {
  console.log('User already exists:', email);

  user.googleId = userInfo.data.id;
  user.authMethod = 'google';
  user.googleAccessToken = tokens.access_token;

  // Refresh token may not always be returned
  if (tokens.refresh_token) {
    user.googleRefreshToken = tokens.refresh_token;
  }

  user.gmailConnected = true;

  await user.save();
}

    // Create JWT token for your app
    const jwtToken = jwt.sign(
      {
        id: user._id,
        name: user.name,
        email: user.email,
      },
      process.env.JWT_SECRET,
      { expiresIn: '7d' }
    );

    // Return success with user data and token
    res.status(200).json({
      success: true,
      message: 'Google login successful',
      token: jwtToken,
      user: {
        id: user._id,
        name: user.name,
        email: user.email,
      },
    });
  } catch (error) {
    console.error('Error during Google OAuth callback:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to complete Google login',
      error: error.message,
    });
  }
});

export default router;